### ISSUE TITLE
triple-quote block text highlighting

### ISSUE THREAD

**Issue by nickrose** [haberdashPI/vscode-python-in-julia#1]
When a particular PyCall syntax is being used a la the following:
```
py"""
import sys
sys.path.append("./")
import util
"""
```
where `./util` is in the current directory of the julia file containing the above code. Currently, there is no syntax highlighting in such a box as the highlighter stands in version 0.1.0

**Comment by haberdashPI** [comment]
Thanks for finding this: a simple workaround, until I figure out a fix, is to add at least two spaces before `py"""`, then it will properly highlight. (I tested the plugin with a full file, where I embedded python inside of functions, and didn't catch this issue, because all of my code was indented).

The reason this happens is because of how docstrings are defined in the [Atom plugin](https://github.com/JuliaEditorSupport/atom-language-julia), which is copied over to the VSCode plugin. Specifically, a custom string literal at the beginning of a line is interpreted as a doc string. (So that `doc"""` works). 

It would be easy to fix this problem by changing the main Julia syntax definition. Perhaps @pfitzseb can speak to whether the developers of Juno would be open to a PR that only treated specific custom string prefixes as docstrings (e.g. `doc`), rather than treating all custom strings as doc strings?

**Comment by nickrose** [comment]
Sure, no worries. Feel free to close this since it's not an issue related to the package itself.

**Comment by pfitzseb** [comment]
> Perhaps @pfitzseb can speak to whether the developers of Juno would be open to a PR that only treated specific custom string prefixes as docstrings (e.g. doc), rather than treating all custom strings as doc strings?

Yeah, sure. Do you wanna prepare a PR or should I?

**Comment by haberdashPI** [comment]
No strong preference; I probably won't have a chance until the weekend to make a PR, so if you have time before then to make the changes, go for it. Otherwise, I can do it then.
